// <auto-generated />
using System;
using FoodBook.Database.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodBook.Database.Migrations.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20190219184004_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("FoodBook.Domain.Entities.Entities.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FoodBook.Domain.Entities.Entities.Recipes.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<Guid>("RecipeId");

                    b.Property<int>("StepNumber");

                    b.HasKey("Id")
                        .HasName("RecipeStepId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("FoodBook.Domain.Entities.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Login");

                    b.Property<string>("SecurityStamp");

                    b.HasKey("Id")
                        .HasName("UserAccountId");

                    b.HasAlternateKey("Email");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("FoodBook.Domain.Entities.Entities.Recipes.RecipeStep", b =>
                {
                    b.HasOne("FoodBook.Domain.Entities.Entities.Recipes.Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
